### ISSUE TITLE
The state estimation is has huge difference compared to ground truth ? 

### ISSUE THREAD

**Issue by shivauchiha** [ori-drs/pronto_anymal_example#10]
Hi the difference between the state estimation and ground truth is large .
![Screenshot from 2020-10-09 08-09-10](https://user-images.githubusercontent.com/41376183/95535918-501c1a80-0a07-11eb-9062-6be55f9dae56.png)

I also have this error are they related  "imu_link" passed to lookupTransform argument target_frame does not exist.?

**Comment by mcamurri** [comment]
Dear @astumpf , the build server is now installed and the demo correctly works on my machine with Ubuntu 20.04 and Noetic. Can you please confirm the demo now works for you?

**Comment by astumpf** [comment]
Important note: We are still working with Ubuntu 18.04 Melodic.

I've just tested today using the noetic branch (with ROS Melodic) as master wasn't updated recently. The install instructions are not clear as "dependencies.rosinstall" is missing the realsense pkg and the "clone_deps.bash" is referring to wrong git branches and duplicates the anymal_b_description in the workspace. So that's what I've came up with:

```
source /opt/ros/melodic/setup.bash

ws_path="/home/alex/pronto_ws"

if [ -d "${ws_path}" ]; then
  echo "Warning: Pronto WS does already exist. Aborting!"
  exit 1
fi

sudo apt install ros-melodic-velodyne-description

# create new catkin workspace
mkdir "${ws_path}"
mkdir "${ws_path}/src"

# init wstool
cd "${ws_path}"
wstool init .

wstool set -y --git "src/pronto"                        "https://github.com/ori-drs/pronto.git" -v "master"
wstool set -y --git "src/pronto_common_utils"           "https://github.com/ori-drs/common_utils.git" -v "master"
wstool set -y --git "src/pronto_anymal_example"         "https://github.com/ori-drs/pronto_anymal_example.git"
wstool set -y --git "src/fovis"                         "https://github.com/ori-drs/fovis.git" -v "master"
wstool set -y --git "src/fovis_ros"                     "https://github.com/ori-drs/fovis_ros.git" -v "pronto-fovis"
wstool set -y --git "src/realsense"                     "https://github.com/ori-drs/realsense.git" -v "development-fixes"

wstool update -j$(nproc)

# install system dependencies
rosdep update
rosdep install -r --from-path . --ignore-src

# build workspace
catkin build

source ${ws_path}/devel/setup.bash
```

Running the demo results in:

![Screenshot from 2021-04-29 11-59-09](https://user-images.githubusercontent.com/7815721/116534478-df751680-a8e2-11eb-8827-ebd4f2a2e1c0.png)

I've noticed that pronto is extremely lagging behind. Maybe a timing issue? However, the error messages I had reported disappeared.

**Comment by mcamurri** [comment]
Dear @astumpf , the dependencies were indeed outdated. The dependency on the realsense2 description can now be easily installed from APT. The noetic branch was also merged some time ago but the branch was not deleted.

If you could have a nother go with the branch for #13 and the usual master for pronto, that would be helpful.

I don't have a melodic machine to test the demo on, but I might be able to have a look over the weekend.

**Comment by wxmerkt** [comment]
This is the result running the entire log:
![image](https://user-images.githubusercontent.com/1664508/117300157-2e85f300-ae71-11eb-964b-a8df6922c807.png)

Is it possible you did not compile your workspace in `Release` or `RelWithDebInfo` mode?

**Comment by astumpf** [comment]
Awesome! Using the `dependencies-fixes` branch fixes all issues. The `clone_deps.sh` scripts works also perfectly. I can now reproduce your results.

There is only one missing run dependencies on `ros-<distro>-image-transport-plugins`. I would suggest adding this to your package manifest, so `rosdep` can install it automatically.

Thank you very much for your efforts!

**Comment by mcamurri** [comment]
Thank you @astumpf for testing it. I've added the package to the branch and merge it soon.

**Comment by sayali-purdue** [comment]
`<exec_depend>image_transport_plugins</exec_depend>` dependency in package.xml is because of the inclusion of a launch file of fovis_ros package in [demo.launch.](https://github.com/ori-drs/pronto_anymal_example/blob/master/pronto_anymal_b/launch/demo.launch#L52) Could you please describe why this run time dependency was added to the package.xml of 'pronto_anymal_b' package and **not** to the package.xml of 'fovis_ros' package?
